# Copyright (c) 2014-present, Facebook, Inc.
"""add health and link distance columns

Revision ID: 0003
Revises: 0002
Create Date: 2020-05-06 21:40:48.989677

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "network_test_result",
        sa.Column(
            "health",
            sa.Enum(
                "EXCELLENT",
                "GOOD",
                "MARGINAL",
                "POOR",
                "MISSING",
                name="networktesthealth",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "network_test_result", sa.Column("link_distance", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("network_test_result", "link_distance")
    op.drop_column("network_test_result", "health")
    # ### end Alembic commands ###
