# Copyright (c) 2014-present, Facebook, Inc.
"""add processing status

Revision ID: 0004
Revises: 0003
Create Date: 2020-06-15 16:27:06.666628

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


old_statuses = ["RUNNING", "FINISHED", "ABORTED", "FAILED"]
new_statuses = old_statuses[:1] + ["PROCESSING"] + old_statuses[1:]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "network_test_execution",
        "status",
        existing_type=sa.Enum(*old_statuses),
        type_=sa.Enum(*new_statuses),
        existing_nullable=False,
    )
    op.alter_column(
        "network_test_result",
        "status",
        existing_type=sa.Enum(*old_statuses),
        type_=sa.Enum(*new_statuses),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "network_test_execution",
        "status",
        existing_type=sa.Enum(*new_statuses),
        type_=sa.Enum(*old_statuses),
        existing_nullable=False,
    )
    op.alter_column(
        "network_test_result",
        "status",
        existing_type=sa.Enum(*new_statuses),
        type_=sa.Enum(*old_statuses),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
