# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""rename mcs samples with traffic column

Revision ID: 0009
Revises: 0008
Create Date: 2021-07-06 21:01:03.409066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "network_test_result",
        column_name="mcs_samples_with_traffic",
        new_column_name="mcs_samples_with_traffic_ratio",
        existing_type=sa.Float(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "network_test_result",
        column_name="mcs_samples_with_traffic_ratio",
        new_column_name="mcs_samples_with_traffic",
        existing_type=sa.Float(),
    )
    # ### end Alembic commands ###
