{
 "title": "Network Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network Name", "query": { "query": "label_values(network)" } },
   {
    "name": "highest_uptime",
    "query": {
     "query": "query_result(topk(3, max_over_time(uptime{network=\"$network\"}[${__range_s}s])))"
    }
   },
   {
    "name": "lowest_uptime",
    "query": {
     "query": "query_result(bottomk(3, max_over_time(uptime{network=\"$network\"}[${__range_s}s])))"
    }
   },
   {
    "name": "best_loadavg",
    "query": {
     "query": "query_result(bottomk(3, avg_over_time(load_15{network=\"$network\"}[${__range_s}s])))"
    }
   },
   {
    "name": "worst_loadavg",
    "query": {
     "query": "query_result(topk(3, avg_over_time(load_15{network=\"$network\"}[${__range_s}s])))"
    }
   },
   {
    "name": "best_memutil",
    "query": {
     "query": "query_result(bottomk(3, avg_over_time(mem_util{network=\"$network\"}[${__range_s}s])))"
    }
   },
   {
    "name": "worst_memutil",
    "query": {
     "query": "query_result(topk(3, avg_over_time(mem_util{network=\"$network\"}[${__range_s}s])))"
    }
   },
   {
    "name": "best_snr",
    "query": {
     "query": "query_result(topk(3, avg_over_time(snr{network=\"$network\", intervalSec=\"30\"}[${__range_s}s])))"
    }
   },
   {
    "name": "worst_snr",
    "query": {
     "query": "query_result(bottomk(3, avg_over_time(snr{network=\"$network\", intervalSec=\"30\"}[${__range_s}s])))"
    }
   },
   {
    "name": "best_numsat",
    "query": {
     "query": "query_result(topk(3, avg_over_time(tgd_gpsstat_fixnumsat{network=\"$network\"}[${__range_s}s])))"
    }
   },
   {
    "name": "worst_numsat",
    "query": {
     "query": "query_result(bottomk(3, avg_over_time(tgd_gpsstat_fixnumsat{network=\"$network\"}[${__range_s}s])))"
    }
   },
   { "name": "link_direction", "query": "A, Z" },
   {
    "name": "pop_list",
    "query": {
     "query": "query_result(avg_over_time(topology_node_is_online{network=\"$network\", pop=\"true\"} [${__range_s}s]))"
    }
   },
   {
    "name": "best_mcs",
    "query": {
     "query": "query_result(topk(3, avg_over_time(mcs{network=\"$network\", intervalSec=\"30\"}[${__range_s}s])))"
    }
   },
   {
    "name": "worst_mcs",
    "query": {
     "query": "query_result(bottomk(3, avg_over_time(mcs{network=\"$network\", intervalSec=\"30\"}[${__range_s}s])))"
    }
   },
   {
    "name": "best_txpower",
    "query": {
     "query": "query_result(bottomk(3, avg_over_time(tx_power{network=\"$network\", intervalSec=\"30\"}[${__range_s}s])))"
    }
   },
   {
    "name": "worst_txpower",
    "query": {
     "query": "query_result(topk(3, avg_over_time(tx_power{network=\"$network\", intervalSec=\"30\"}[${__range_s}s])))"
    }
   },
   {
    "name": "best_per",
    "query": {
     "query": "query_result(bottomk(3, avg_over_time(per{network=\"$network\", intervalSec=\"30\"}[${__range_s}s])))"
    }
   },
   {
    "name": "worst_per",
    "query": {
     "query": "query_result(topk(3, avg_over_time(per{network=\"$network\", intervalSec=\"30\"}[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Online",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topology_online_nodes_ratio{network=\"$network\"} * 100",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "sum(topology_node_is_online{network=\"$network\", pop=\"true\"}) / scalar(topology_pop_nodes_total{network=\"$network\"}) * 100",
     "legendFormat": "POP Nodes"
    }
   ]
  },
  {
   "title": "Links Online",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topology_online_wireless_links_ratio{network=\"$network\"} * 100",
     "legendFormat": "Online Links"
    },
    {
     "expr": "sum(irate(topology_link_is_online{network=\"$network\"}[5m])) * 60",
     "legendFormat": "Flaps / m"
    }
   ]
  },
  {
   "title": "Link Ignition Attempts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(topology_link_attempts{network=\"$network\", cn=\"false\"}[5m])) * 60",
     "legendFormat": "DN-DN / m"
    },
    {
     "expr": "sum(rate(topology_link_attempts{network=\"$network\", cn=\"true\"}[5m])) * 60",
     "legendFormat": "DN-CN / m"
    }
   ]
  },
  {
   "title": "Ping Loss",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(udp_pinger_loss_ratio{intervalSec=\"30\", cn=\"false\", nodeName!=\"\"}) / count(udp_pinger_loss_ratio{intervalSec=\"30\", cn=\"false\", nodeName!=\"\"})",
     "legendFormat": "DN"
    },
    {
     "expr": "sum(udp_pinger_loss_ratio{intervalSec=\"30\", cn=\"true\", nodeName!=\"\"}) / count(udp_pinger_loss_ratio{intervalSec=\"30\", cn=\"true\", nodeName!=\"\"})",
     "legendFormat": "CN"
    }
   ]
  },
  {
   "title": "POP BGP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(e2e_minion_bgp_online_bgp_peers{network=\"$network\", pop=\"true\"}) / scalar(topology_pop_nodes_total{network=\"$network\"})) * 100",
     "legendFormat": "BGP Peers"
    },
    {
     "expr": "sum(irate(e2e_minion_bgp_online_bgp_peers{network=\"$network\", pop=\"true\"}[10m])) * 60",
     "legendFormat": "Flaps / m"
    }
   ]
  },
  {
   "title": "Default Routes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(drs_cn_egress_routes_count{network=\"$network\"} > 0) / sum (topology_link_is_online{network=\"$network\"})",
     "legendFormat": "Links with CN traffic"
    },
    {
     "expr": "sum(irate(drs_default_routes_changed{network=\"$network\"}[5m])) * 60",
     "legendFormat": "Flaps / m"
    }
   ]
  },
  {
   "title": "FIB Summary",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(avg(fib_num_routes{network=\"$network\"}))",
     "legendFormat": "Number of Routes"
    },
    {
     "expr": "sum(irate(fib_num_routes{network=\"$network\"}[10m])) * 60",
     "legendFormat": "Flaps / m"
    }
   ]
  },
  {
   "title": "QoS Traffic Class",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"vpp_qos_terra._tc0_packets\", network=\"$network\"})",
     "legendFormat": "tc0"
    },
    {
     "expr": "sum({__name__=~\"vpp_qos_terra._tc1_packets\", network=\"$network\"})",
     "legendFormat": "tc1"
    },
    {
     "expr": "sum({__name__=~\"vpp_qos_terra._tc2_packets\", network=\"$network\"})",
     "legendFormat": "tc2"
    },
    {
     "expr": "sum({__name__=~\"vpp_qos_terra._tc3_packets\", network=\"$network\"})",
     "legendFormat": "tc3"
    }
   ]
  },
  {
   "title": "Network RF Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rx_bytes{network=\"$network\"}) * 8",
     "legendFormat": "RX bps"
    },
    {
     "expr": "sum(tx_bytes{network=\"$network\"}) * 8",
     "legendFormat": "TX bps"
    }
   ]
  },
  {
   "title": "POP VPP Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(tengigabitethernet0_if_tx_bytes{pop=\"true\",network=\"$network\"}) * 8",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(tengigabitethernet0_if_rx_bytes{pop=\"true\",network=\"$network\"}) * 8",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Links Online",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(topology_link_is_online{network=\"$network\"}) * 100",
     "legendFormat": "% online"
    },
    {
     "expr": "count(irate(topology_link_attempts{network=\"$network\"}[5m]) > 0)",
     "legendFormat": "Link Attempts (Count)"
    }
   ]
  },
  {
   "title": "Nodes Online",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(topology_node_is_online{network=\"$network\"}) * 100",
     "legendFormat": "% online"
    },
    {
     "expr": "udp_pinger_loss_ratio{network=\"$network\", intervalSec=\"30\", nodeName=\"\"}",
     "legendFormat": "% Ping Loss"
    }
   ]
  },
  {
   "title": "VxLAN Tunnels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(tunnels_num_tunnels{network=\"$network\"})",
     "legendFormat": "Count"
    },
    {
     "expr": "sum(rate({__name__=~\"vxlan_tunnel._if_tx_bytes\", network=\"$network\"}[5m])) * 8",
     "legendFormat": "TX bps"
    },
    {
     "expr": "sum(rate({__name__=~\"vxlan_tunnel._if_rx_bytes\", network=\"$network\"}[5m])) * 8",
     "legendFormat": "RX bps"
    }
   ]
  },
  {
   "title": "POP VPP Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(tengigabitethernet0_if_tx_error_pkts{pop=\"true\",network=\"$network\"})",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(tengigabitethernet0_if_rx_error_pkts{pop=\"true\",network=\"$network\"})",
     "legendFormat": "RX"
    }
   ]
  },
  { "title": "Best vs Worst", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Best vs Worst SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "snr{network=\"$network\", intervalSec=\"30\", linkName=~\"$best_snr\"}",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Best)"
    },
    {
     "expr": "snr{network=\"$network\", intervalSec=\"30\", linkName=~\"$worst_snr\"} ",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Worst)"
    }
   ]
  },
  {
   "title": "Best vs Worst MCS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mcs{network=\"$network\", intervalSec=\"30\", linkName=~\"$best_mcs\"}",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Best)"
    },
    {
     "expr": "mcs{network=\"$network\", intervalSec=\"30\", linkName=~\"$worst_mcs\"} ",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Worst)"
    }
   ]
  },
  {
   "title": "Best vs Worst RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rssi{network=\"$network\", intervalSec=\"30\", linkName=~\"$best_snr\", linkDirection=~\"$link_direction\"}",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Best)"
    },
    {
     "expr": "rssi{network=\"$network\", intervalSec=\"30\", linkName=~\"$worst_snr\", linkDirection=~\"$link_direction\"}",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Worst)"
    }
   ]
  },
  {
   "title": "Best vs Worst TX Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tx_power{network=\"$network\", intervalSec=\"30\", linkName=~\"$best_txpower\"}",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Best)"
    },
    {
     "expr": "tx_power{network=\"$network\", intervalSec=\"30\", linkName=~\"$worst_txpower\"}",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Worst)"
    }
   ]
  },
  {
   "title": "Best vs Worst Satellites Fixed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tgd_gpsstat_fixnumsat{network=\"$network\", nodeName=~\"$best_numsat\"}",
     "legendFormat": "{{nodeName}} (Best)"
    },
    {
     "expr": "tgd_gpsstat_fixnumsat{network=\"$network\", nodeName=~\"$worst_numsat\"}",
     "legendFormat": "{{nodeName}} (Worst)"
    }
   ]
  },
  {
   "title": "Best vs Worst PER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "per{network=\"$network\", intervalSec=\"30\", linkName=~\"$best_per\"} / 1000000",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Best)"
    },
    {
     "expr": "per{network=\"$network\", intervalSec=\"30\", linkName=~\"$worst_per\"} / 1000000",
     "legendFormat": "{{linkName}} ({{linkDirection}}) (Worst)"
    }
   ]
  },
  {
   "title": "FIB Route Count Change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(fib_num_routes{network=\"$network\"}[10m]) != 0",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "Best vs Worst Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "uptime{network=\"$network\", intervalSec=\"30\", nodeName=~\"$highest_uptime\"}",
     "legendFormat": "{{nodeName}} (Best)"
    },
    {
     "expr": "uptime{network=\"$network\", intervalSec=\"30\", nodeName=~\"$lowest_uptime\"}",
     "legendFormat": "{{nodeName}} (Worst)"
    }
   ]
  },
  {
   "title": "Best vs Worst Load Averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "load_15{network=\"$network\", intervalSec=\"30\", nodeName=~\"$best_loadavg\"}",
     "legendFormat": "{{nodeName}} (Best)"
    },
    {
     "expr": "load_15{network=\"$network\", intervalSec=\"30\", nodeName=~\"$worst_loadavg\"}",
     "legendFormat": "{{nodeName}} (Worst)"
    }
   ]
  },
  {
   "title": "Best vs Worst Memory Util %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mem_util{network=\"$network\", intervalSec=\"30\", nodeName=~\"$best_memutil\"}",
     "legendFormat": "{{nodeName}} (Best)"
    },
    {
     "expr": "mem_util{network=\"$network\", intervalSec=\"30\", nodeName=~\"$worst_memutil\"}",
     "legendFormat": "{{nodeName}} (Worst)"
    }
   ]
  }
 ]
}