{
 "title": "Node Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Topology", "query": { "query": "label_values(network)" } },
   {
    "name": "link_name",
    "label": "Select Link",
    "query": {
     "query": "label_values(snr{network=\"$network\"}, linkName)"
    }
   },
   {
    "name": "nodeA_name",
    "label": "Node A",
    "query": {
     "query": "label_values(snr{network=\"$network\",linkName=\"$link_name\"}, nodeName)"
    }
   },
   {
    "name": "nodeZ_name",
    "label": "Node Z",
    "query": {
     "query": "label_values(snr{network=\"$network\",linkName=\"$link_name\",nodeName!=\"$nodeA_name\"}, nodeName)"
    }
   },
   {
    "name": "nodeA",
    "label": "nodeA (no select)",
    "query": {
     "query": "label_values(snr{network=\"$network\",nodeName=\"$nodeA_name\"}, radioMac)"
    }
   },
   {
    "name": "nodeZ",
    "label": "nodeZ (no select)",
    "query": {
     "query": "label_values(snr{network=\"$network\",linkName=\"$link_name\",nodeName=\"$nodeZ_name\"}, radioMac)"
    }
   },
   { "name": "intervalSec", "label": "write interval (sec)", "query": "1,30" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load Averages - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "load_1{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "1 min"
    },
    {
     "expr": "load_5{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "5 min"
    },
    {
     "expr": "load_15{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "Load Averages - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "load_1{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "1 min"
    },
    {
     "expr": "load_5{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "5 min"
    },
    {
     "expr": "load_15{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "Total Processes - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "procs_total{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "1 min"
    }
   ]
  },
  {
   "title": "Total Processes - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "procs_total{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "1 min"
    }
   ]
  },
  {
   "title": "CPU Usage - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Util %"
    },
    {
     "expr": "cpu_sys{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Sys %"
    },
    {
     "expr": "cpu_user{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "User %"
    },
    {
     "expr": "cpu_wait{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Wait %"
    }
   ]
  },
  {
   "title": "CPU Usage - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Util %"
    },
    {
     "expr": "cpu_sys{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Sys %"
    },
    {
     "expr": "cpu_user{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "User %"
    },
    {
     "expr": "cpu_wait{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Wait %"
    }
   ]
  },
  {
   "title": "Node Memory - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mem_total{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "mem_free{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "mem_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Util %"
    }
   ]
  },
  {
   "title": "Node Memory - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mem_total{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "mem_free{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "mem_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Util %"
    }
   ]
  },
  { "title": "System Process Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "E2E Minion, Open/R, Stats Agent - CPU Util - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_cpu_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "E2E"
    },
    {
     "expr": "openr_cpu_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Open/R"
    },
    {
     "expr": "stats_agent_cpu_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Stats"
    }
   ]
  },
  {
   "title": "E2E Minion, Open/R, Stats Agent - CPU Util - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_cpu_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "E2E Minion"
    },
    {
     "expr": "openr_cpu_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Open/R"
    },
    {
     "expr": "stats_agent_cpu_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Stats Agent"
    }
   ]
  },
  {
   "title": "E2E Minion, Open/R, Stats Agent - Memory Util - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_mem_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "E2E Minion"
    },
    {
     "expr": "openr_mem_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Open/R"
    },
    {
     "expr": "stats_agent_mem_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Stats Agent"
    }
   ]
  },
  {
   "title": "E2E Minion, Open/R, Stats Agent - Memory Util - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_mem_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "E2E Minion"
    },
    {
     "expr": "openr_mem_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Open/R"
    },
    {
     "expr": "stats_agent_mem_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Stats Agent"
    }
   ]
  },
  { "title": "System Process Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Open/R Performance - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "openr_cpu_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "openr_mem_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "MEM %"
    },
    {
     "expr": "openr_uptime{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Open/R Performance - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "openr_cpu_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "openr_mem_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "MEM %"
    },
    {
     "expr": "openr_uptime{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Open/R Metrics - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "fib_convergence_time_ms_avg_0{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "FIB Convergence Time (ms)"
    },
    {
     "expr": "fib_thrift_failure_add_del_route_count_0{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "FIB Thrift Add/Del Failure (count)"
    },
    {
     "expr": "fib_thrift_failure_keepalive_count_0{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "FIB Thrift Keepalive Failure (count)"
    }
   ]
  },
  {
   "title": "Open/R Metrics - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "fib_convergence_time_ms_avg_0{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "FIB Convergence Time (ms)"
    },
    {
     "expr": "fib_thrift_failure_add_del_route_count_0{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "FIB Thrift Add/Del Failure (count)"
    },
    {
     "expr": "fib_thrift_failure_keepalive_count_0{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "FIB Thrift Keepalive Failure (count)"
    }
   ]
  },
  {
   "title": "Open/R Adjacencies - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "link_monitor_adjacencies{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Adjacencies (count)"
    },
    {
     "expr": "link_monitor_neighbor_down_sum_0{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Neighbor Down (count)"
    }
   ]
  },
  {
   "title": "Open/R Adjacencies - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "link_monitor_adjacencies{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Adjacencies (count)"
    },
    {
     "expr": "link_monitor_neighbor_down_sum_0{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Neighbor Down (count)"
    }
   ]
  },
  {
   "title": "E2E Minion Performance - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_cpu_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "e2e_minion_mem_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "MEM %"
    },
    {
     "expr": "e2e_minion_uptime{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "E2E Minion Performance - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_cpu_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "e2e_minion_mem_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "MEM %"
    },
    {
     "expr": "e2e_minion_uptime{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Stats Agent Performance - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stats_agent_cpu_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "stats_agent_mem_util{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "MEM %"
    }
   ]
  },
  {
   "title": "Stats Agent Performance - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stats_agent_cpu_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "stats_agent_mem_util{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "MEM %"
    }
   ]
  },
  {
   "title": "/ Storage - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mount_free:_{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "MB Free"
    },
    {
     "expr": "mount_util:_{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "MB %"
    }
   ]
  },
  {
   "title": "/ Storage - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mount_free:_{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "MB Free"
    },
    {
     "expr": "mount_util:_{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "MB %"
    }
   ]
  },
  {
   "title": "/data Storage - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mount_free:_data{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "MB Free"
    },
    {
     "expr": "mount_util:_data{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "MB %"
    }
   ]
  },
  {
   "title": "/data Storage - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mount_free:_data{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "MB Free"
    },
    {
     "expr": "mount_util:_data{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "MB %"
    }
   ]
  },
  { "title": "GPS Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "GPS - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgd_gpsstat_fixnumsat{network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "GPS Satellites Fixed"
    },
    {
     "expr": "sum(tgf_00:00:00:00:00:00_miscsys_gpstorf{network=\"$network\", nodeName=\"$nodeA_name\"})",
     "legendFormat": "GPS to RF Transitions"
    }
   ]
  },
  {
   "title": "GPS - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgd_gpsstat_fixnumsat{network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "GPS Satellites Fixed"
    },
    {
     "expr": "sum(tgf_00:00:00:00:00:00_miscsys_gpstorf{network=\"$network\", nodeName=\"$nodeA_name\"})",
     "legendFormat": "GPS to RF Transitions"
    }
   ]
  },
  { "title": "Uptime and Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "E2E Minion & Node Uptime, Percentage Node Availability - $nodeA_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_uptime{nodeName=\"[[nodeA_name]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "E2E Minion Uptime"
    },
    {
     "expr": "uptime{nodeName=\"[[nodeA_name]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "Node Uptime"
    },
    {
     "expr": "1 - udp_pinger_loss_ratio{intervalSec=\"$intervalSec\", network=\"$network\", nodeName=\"$nodeA_name\"}",
     "legendFormat": "Node Availability"
    }
   ]
  },
  {
   "title": "E2E Minion & Node Uptime, Percentage Node Availability - $nodeZ_name (${__from:date} -- ${__to:date})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_uptime{nodeName=\"[[nodeZ_name]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "E2E Minion Uptime"
    },
    {
     "expr": "uptime{nodeName=\"[[nodeZ_name]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "Node Uptime"
    },
    {
     "expr": "1 - udp_pinger_loss_ratio{intervalSec=\"$intervalSec\", network=\"$network\", nodeName=\"$nodeZ_name\"}",
     "legendFormat": "Node Availability"
    }
   ]
  }
 ]
}