{
 "title": "Network Health",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "networkName", "label": "Network Name", "query": "label_values(network)" }
  ]
 },
 "panels": [
  {
   "title": "Nodes Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "online_nodes_perc{network=\"$networkName\"}"
    }
   ]
  },
  {
   "title": "Links Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "online_wireless_links_perc{network=\"$networkName\"}"
    }
   ]
  },
  {
   "title": "Network RF Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "expr": "sum(tx_bytes)", "legendFormat": "bps" }
   ]
  },
  {
   "title": "Links Online",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(link_online{network=\"$networkName\",cn=\"false\"}) * 100",
     "legendFormat": "% online"
    }
   ]
  },
  {
   "title": "Nodes Online",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_online{network=\"$networkName\"}) * 100",
     "legendFormat": "% online"
    }
   ]
  },
  { "title": "Ruckus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Ruckus Client Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wap_client_count{registrationState=\"Approved\"}) by (name)",
     "legendFormat": "$(name)"
    }
   ]
  },
  {
   "title": "WAP Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    { "expr": "sum(wap_uptime) by (name)", "legendFormat": "$(name)" }
   ]
  },
  { "title": "Aggregates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "dB" }
   ],
   "targets": [
    {
     "expr": "rssi{network=\"$networkName\"}",
     "legendFormat": "$(link) ($(linkDirection))"
    }
   ]
  },
  {
   "title": "SnR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "snr{network=\"$networkName\"}",
     "legendFormat": "$(link) ($(linkDirection))"
    }
   ]
  },
  {
   "title": "PER",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "per{network=\"$networkName\"}",
     "legendFormat": "$(link) ($(linkDirection))"
    }
   ]
  },
  {
   "title": "MCS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mcs{network=\"$networkName\"}",
     "legendFormat": "$(link) ($(linkDirection))"
    }
   ]
  }
 ]
}