# Generated by Django 2.1.1 on 2018-10-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0005_testrunexecution_expected_end_time")]

    operations = [
        migrations.AlterField(
            model_name="testrunexecution",
            name="expected_end_time",
            field=models.IntegerField(default=1539283248.2099714),
        )
    ]
