# Generated by Django 2.1.1 on 2019-03-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190308_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunexecution',
            name='expected_end_time',
            field=models.IntegerField(null=True),
        ),
    ]
