"""create history and link cn routes tables

Revision ID: 0000
Revises:
Create Date: 2020-01-28 18:00:15.348862

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0000"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """ commands auto generated by Alembic - please adjust! """
    op.create_table(
        "default_routes_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("network_name", sa.String(length=100), nullable=False),
        sa.Column("node_name", sa.String(length=255), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("routes", sa.JSON(), nullable=False),
        sa.Column("hop_count", sa.Integer(), nullable=False),
        sa.Column("prev_routes_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prev_routes_id"], ["default_routes_history.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_default_routes_history_last_updated"),
        "default_routes_history",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_routes_history_network_name"),
        "default_routes_history",
        ["network_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_routes_history_node_name"),
        "default_routes_history",
        ["node_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_routes_history_prev_routes_id"),
        "default_routes_history",
        ["prev_routes_id"],
        unique=False,
    )
    op.create_table(
        "link_cn_routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("network_name", sa.String(length=100), nullable=False),
        sa.Column("link_name", sa.String(length=255), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cn_routes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_link_cn_routes_last_updated"),
        "link_cn_routes",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_link_cn_routes_link_name"),
        "link_cn_routes",
        ["link_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_link_cn_routes_network_name"),
        "link_cn_routes",
        ["network_name"],
        unique=False,
    )
    """ end Alembic commands """


def downgrade():
    """ commands auto generated by Alembic - please adjust! """
    op.drop_index(op.f("ix_link_cn_routes_network_name"), table_name="link_cn_routes")
    op.drop_index(op.f("ix_link_cn_routes_link_name"), table_name="link_cn_routes")
    op.drop_index(op.f("ix_link_cn_routes_last_updated"), table_name="link_cn_routes")
    op.drop_table("link_cn_routes")
    op.drop_index(
        op.f("ix_default_routes_history_prev_routes_id"),
        table_name="default_routes_history",
    )
    op.drop_index(
        op.f("ix_default_routes_history_node_name"), table_name="default_routes_history"
    )
    op.drop_index(
        op.f("ix_default_routes_history_network_name"),
        table_name="default_routes_history",
    )
    op.drop_index(
        op.f("ix_default_routes_history_last_updated"),
        table_name="default_routes_history",
    )
    op.drop_table("default_routes_history")
    """ end Alembic commands """
