#!/bin/bash
if [ -z "$E2E_TOPOLOGY_FILE" ] || [ ! -f "$E2E_TOPOLOGY_FILE" ]; then
  echo "E2E_TOPOLOGY_FILE not set or not found"
  exit 1
fi
if [ -z "$E2E_ROOTFS" ] || [ ! -d "$E2E_ROOTFS" ]; then
  echo "E2E_ROOTFS not set or not found"
  exit 1
fi
# copy topology file from chroot
cp -v "${E2E_ROOTFS}/etc/e2e_config/topology.conf" "$E2E_TOPOLOGY_FILE"
