//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
const thrift = require('thrift');
const Thrift = thrift.Thrift;
const Q = thrift.Q;

const beringei_data_ttypes = require('./beringei_data_types');


const ttypes = module.exports = {};
