//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


const thrift = require('thrift');
const Thrift = thrift.Thrift;
const Q = thrift.Q;

const FwOptParams_ttypes = require('./FwOptParams_types');


const ttypes = module.exports = {};
const SystemParams = module.exports.SystemParams = function(args) {
  this.managedConfig = null;
  if (args) {
    if (args.managedConfig !== undefined && args.managedConfig !== null) {
      this.managedConfig = args.managedConfig;
    }
  }
};
SystemParams.prototype = {};
SystemParams.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    const ret = input.readFieldBegin();
    const fname = ret.fname;
    const ftype = ret.ftype;
    const fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.managedConfig = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SystemParams.prototype.write = function(output) {
  output.writeStructBegin('SystemParams');
  if (this.managedConfig !== null && this.managedConfig !== undefined) {
    output.writeFieldBegin('managedConfig', Thrift.Type.BOOL, 1);
    output.writeBool(this.managedConfig);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

const NodeEnvParams = module.exports.NodeEnvParams = function(args) {
  this.OPENR_ENABLED = null;
  this.OPENR_ALLOC_PREFIX = null;
  this.OPENR_USE_RTT_METRIC = null;
  this.OPENR_USE_FIB_NSS = null;
  this.OOB_NETNS = null;
  this.OOB_INTERFACE = null;
  this.CPE_INTERFACE = null;
  this.E2E_ENABLED = null;
  this.FW_IF2IF = null;
  this.OPENR_DOMAIN = null;
  this.FB_DRIVER_VERBOSE = null;
  this.HMAC_VERBOSE = null;
  this.KMOD_VERBOSE = null;
  if (args) {
    if (args.OPENR_ENABLED !== undefined && args.OPENR_ENABLED !== null) {
      this.OPENR_ENABLED = args.OPENR_ENABLED;
    }
    if (args.OPENR_ALLOC_PREFIX !== undefined && args.OPENR_ALLOC_PREFIX !== null) {
      this.OPENR_ALLOC_PREFIX = args.OPENR_ALLOC_PREFIX;
    }
    if (args.OPENR_USE_RTT_METRIC !== undefined && args.OPENR_USE_RTT_METRIC !== null) {
      this.OPENR_USE_RTT_METRIC = args.OPENR_USE_RTT_METRIC;
    }
    if (args.OPENR_USE_FIB_NSS !== undefined && args.OPENR_USE_FIB_NSS !== null) {
      this.OPENR_USE_FIB_NSS = args.OPENR_USE_FIB_NSS;
    }
    if (args.OOB_NETNS !== undefined && args.OOB_NETNS !== null) {
      this.OOB_NETNS = args.OOB_NETNS;
    }
    if (args.OOB_INTERFACE !== undefined && args.OOB_INTERFACE !== null) {
      this.OOB_INTERFACE = args.OOB_INTERFACE;
    }
    if (args.CPE_INTERFACE !== undefined && args.CPE_INTERFACE !== null) {
      this.CPE_INTERFACE = args.CPE_INTERFACE;
    }
    if (args.E2E_ENABLED !== undefined && args.E2E_ENABLED !== null) {
      this.E2E_ENABLED = args.E2E_ENABLED;
    }
    if (args.FW_IF2IF !== undefined && args.FW_IF2IF !== null) {
      this.FW_IF2IF = args.FW_IF2IF;
    }
    if (args.OPENR_DOMAIN !== undefined && args.OPENR_DOMAIN !== null) {
      this.OPENR_DOMAIN = args.OPENR_DOMAIN;
    }
    if (args.FB_DRIVER_VERBOSE !== undefined && args.FB_DRIVER_VERBOSE !== null) {
      this.FB_DRIVER_VERBOSE = args.FB_DRIVER_VERBOSE;
    }
    if (args.HMAC_VERBOSE !== undefined && args.HMAC_VERBOSE !== null) {
      this.HMAC_VERBOSE = args.HMAC_VERBOSE;
    }
    if (args.KMOD_VERBOSE !== undefined && args.KMOD_VERBOSE !== null) {
      this.KMOD_VERBOSE = args.KMOD_VERBOSE;
    }
  }
};
NodeEnvParams.prototype = {};
NodeEnvParams.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    const ret = input.readFieldBegin();
    const fname = ret.fname;
    const ftype = ret.ftype;
    const fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.OPENR_ENABLED = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.OPENR_ALLOC_PREFIX = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.OPENR_USE_RTT_METRIC = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.OPENR_USE_FIB_NSS = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.OOB_NETNS = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRING) {
        this.OOB_INTERFACE = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRING) {
        this.CPE_INTERFACE = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRING) {
        this.E2E_ENABLED = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.STRING) {
        this.FW_IF2IF = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.STRING) {
        this.OPENR_DOMAIN = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 11:
      if (ftype == Thrift.Type.STRING) {
        this.FB_DRIVER_VERBOSE = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 12:
      if (ftype == Thrift.Type.STRING) {
        this.HMAC_VERBOSE = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 13:
      if (ftype == Thrift.Type.STRING) {
        this.KMOD_VERBOSE = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

NodeEnvParams.prototype.write = function(output) {
  output.writeStructBegin('NodeEnvParams');
  if (this.OPENR_ENABLED !== null && this.OPENR_ENABLED !== undefined) {
    output.writeFieldBegin('OPENR_ENABLED', Thrift.Type.STRING, 1);
    output.writeString(this.OPENR_ENABLED);
    output.writeFieldEnd();
  }
  if (this.OPENR_ALLOC_PREFIX !== null && this.OPENR_ALLOC_PREFIX !== undefined) {
    output.writeFieldBegin('OPENR_ALLOC_PREFIX', Thrift.Type.STRING, 2);
    output.writeString(this.OPENR_ALLOC_PREFIX);
    output.writeFieldEnd();
  }
  if (this.OPENR_USE_RTT_METRIC !== null && this.OPENR_USE_RTT_METRIC !== undefined) {
    output.writeFieldBegin('OPENR_USE_RTT_METRIC', Thrift.Type.STRING, 3);
    output.writeString(this.OPENR_USE_RTT_METRIC);
    output.writeFieldEnd();
  }
  if (this.OPENR_USE_FIB_NSS !== null && this.OPENR_USE_FIB_NSS !== undefined) {
    output.writeFieldBegin('OPENR_USE_FIB_NSS', Thrift.Type.STRING, 4);
    output.writeString(this.OPENR_USE_FIB_NSS);
    output.writeFieldEnd();
  }
  if (this.OOB_NETNS !== null && this.OOB_NETNS !== undefined) {
    output.writeFieldBegin('OOB_NETNS', Thrift.Type.STRING, 5);
    output.writeString(this.OOB_NETNS);
    output.writeFieldEnd();
  }
  if (this.OOB_INTERFACE !== null && this.OOB_INTERFACE !== undefined) {
    output.writeFieldBegin('OOB_INTERFACE', Thrift.Type.STRING, 6);
    output.writeString(this.OOB_INTERFACE);
    output.writeFieldEnd();
  }
  if (this.CPE_INTERFACE !== null && this.CPE_INTERFACE !== undefined) {
    output.writeFieldBegin('CPE_INTERFACE', Thrift.Type.STRING, 7);
    output.writeString(this.CPE_INTERFACE);
    output.writeFieldEnd();
  }
  if (this.E2E_ENABLED !== null && this.E2E_ENABLED !== undefined) {
    output.writeFieldBegin('E2E_ENABLED', Thrift.Type.STRING, 8);
    output.writeString(this.E2E_ENABLED);
    output.writeFieldEnd();
  }
  if (this.FW_IF2IF !== null && this.FW_IF2IF !== undefined) {
    output.writeFieldBegin('FW_IF2IF', Thrift.Type.STRING, 9);
    output.writeString(this.FW_IF2IF);
    output.writeFieldEnd();
  }
  if (this.OPENR_DOMAIN !== null && this.OPENR_DOMAIN !== undefined) {
    output.writeFieldBegin('OPENR_DOMAIN', Thrift.Type.STRING, 10);
    output.writeString(this.OPENR_DOMAIN);
    output.writeFieldEnd();
  }
  if (this.FB_DRIVER_VERBOSE !== null && this.FB_DRIVER_VERBOSE !== undefined) {
    output.writeFieldBegin('FB_DRIVER_VERBOSE', Thrift.Type.STRING, 11);
    output.writeString(this.FB_DRIVER_VERBOSE);
    output.writeFieldEnd();
  }
  if (this.HMAC_VERBOSE !== null && this.HMAC_VERBOSE !== undefined) {
    output.writeFieldBegin('HMAC_VERBOSE', Thrift.Type.STRING, 12);
    output.writeString(this.HMAC_VERBOSE);
    output.writeFieldEnd();
  }
  if (this.KMOD_VERBOSE !== null && this.KMOD_VERBOSE !== undefined) {
    output.writeFieldBegin('KMOD_VERBOSE', Thrift.Type.STRING, 13);
    output.writeString(this.KMOD_VERBOSE);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

const PopConfigParams = module.exports.PopConfigParams = function(args) {
  this.POP_ADDR = null;
  this.POP_IFACE = null;
  this.POP_STATIC_ROUTING = null;
  this.POP_BGP_ROUTING = null;
  this.GW_ADDR = null;
  if (args) {
    if (args.POP_ADDR !== undefined && args.POP_ADDR !== null) {
      this.POP_ADDR = args.POP_ADDR;
    }
    if (args.POP_IFACE !== undefined && args.POP_IFACE !== null) {
      this.POP_IFACE = args.POP_IFACE;
    }
    if (args.POP_STATIC_ROUTING !== undefined && args.POP_STATIC_ROUTING !== null) {
      this.POP_STATIC_ROUTING = args.POP_STATIC_ROUTING;
    }
    if (args.POP_BGP_ROUTING !== undefined && args.POP_BGP_ROUTING !== null) {
      this.POP_BGP_ROUTING = args.POP_BGP_ROUTING;
    }
    if (args.GW_ADDR !== undefined && args.GW_ADDR !== null) {
      this.GW_ADDR = args.GW_ADDR;
    }
  }
};
PopConfigParams.prototype = {};
PopConfigParams.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    const ret = input.readFieldBegin();
    const fname = ret.fname;
    const ftype = ret.ftype;
    const fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.POP_ADDR = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.POP_IFACE = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.POP_STATIC_ROUTING = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.POP_BGP_ROUTING = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.GW_ADDR = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PopConfigParams.prototype.write = function(output) {
  output.writeStructBegin('PopConfigParams');
  if (this.POP_ADDR !== null && this.POP_ADDR !== undefined) {
    output.writeFieldBegin('POP_ADDR', Thrift.Type.STRING, 1);
    output.writeString(this.POP_ADDR);
    output.writeFieldEnd();
  }
  if (this.POP_IFACE !== null && this.POP_IFACE !== undefined) {
    output.writeFieldBegin('POP_IFACE', Thrift.Type.STRING, 2);
    output.writeString(this.POP_IFACE);
    output.writeFieldEnd();
  }
  if (this.POP_STATIC_ROUTING !== null && this.POP_STATIC_ROUTING !== undefined) {
    output.writeFieldBegin('POP_STATIC_ROUTING', Thrift.Type.STRING, 3);
    output.writeString(this.POP_STATIC_ROUTING);
    output.writeFieldEnd();
  }
  if (this.POP_BGP_ROUTING !== null && this.POP_BGP_ROUTING !== undefined) {
    output.writeFieldBegin('POP_BGP_ROUTING', Thrift.Type.STRING, 4);
    output.writeString(this.POP_BGP_ROUTING);
    output.writeFieldEnd();
  }
  if (this.GW_ADDR !== null && this.GW_ADDR !== undefined) {
    output.writeFieldBegin('GW_ADDR', Thrift.Type.STRING, 5);
    output.writeString(this.GW_ADDR);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

const LogTailSource = module.exports.LogTailSource = function(args) {
  this.enabled = null;
  this.filename = null;
  if (args) {
    if (args.enabled !== undefined && args.enabled !== null) {
      this.enabled = args.enabled;
    }
    if (args.filename !== undefined && args.filename !== null) {
      this.filename = args.filename;
    }
  }
};
LogTailSource.prototype = {};
LogTailSource.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    const ret = input.readFieldBegin();
    const fname = ret.fname;
    const ftype = ret.ftype;
    const fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.enabled = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.filename = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LogTailSource.prototype.write = function(output) {
  output.writeStructBegin('LogTailSource');
  if (this.enabled !== null && this.enabled !== undefined) {
    output.writeFieldBegin('enabled', Thrift.Type.BOOL, 1);
    output.writeBool(this.enabled);
    output.writeFieldEnd();
  }
  if (this.filename !== null && this.filename !== undefined) {
    output.writeFieldBegin('filename', Thrift.Type.STRING, 2);
    output.writeString(this.filename);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

const LogTailParams = module.exports.LogTailParams = function(args) {
  this.sources = null;
  if (args) {
    if (args.sources !== undefined && args.sources !== null) {
      this.sources = Thrift.copyMap(args.sources, [ttypes.LogTailSource]);
    }
  }
};
LogTailParams.prototype = {};
LogTailParams.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    const ret = input.readFieldBegin();
    const fname = ret.fname;
    const ftype = ret.ftype;
    const fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.MAP) {
        let _size0 = 0;
        var _rtmp34;
        this.sources = {};
        let _ktype1 = 0;
        let _vtype2 = 0;
        _rtmp34 = input.readMapBegin();
        _ktype1 = _rtmp34.ktype;
        _vtype2 = _rtmp34.vtype;
        _size0 = _rtmp34.size;
        for (let _i5 = 0; _i5 < _size0; ++_i5) {
          let key6 = null;
          let val7 = null;
          key6 = input.readString();
          val7 = new ttypes.LogTailSource();
          val7.read(input);
          this.sources[key6] = val7;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LogTailParams.prototype.write = function(output) {
  output.writeStructBegin('LogTailParams');
  if (this.sources !== null && this.sources !== undefined) {
    output.writeFieldBegin('sources', Thrift.Type.MAP, 1);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRUCT, Thrift.objectLength(this.sources));
    for (const kiter8 in this.sources) {
      if (this.sources.hasOwnProperty(kiter8)) {
        const viter9 = this.sources[kiter8];
        output.writeString(kiter8);
        viter9.write(output);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

const StatsAgentSource = module.exports.StatsAgentSource = function(args) {
  this.enabled = null;
  this.zmq_url = null;
  if (args) {
    if (args.enabled !== undefined && args.enabled !== null) {
      this.enabled = args.enabled;
    }
    if (args.zmq_url !== undefined && args.zmq_url !== null) {
      this.zmq_url = args.zmq_url;
    }
  }
};
StatsAgentSource.prototype = {};
StatsAgentSource.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    const ret = input.readFieldBegin();
    const fname = ret.fname;
    const ftype = ret.ftype;
    const fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.enabled = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.zmq_url = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatsAgentSource.prototype.write = function(output) {
  output.writeStructBegin('StatsAgentSource');
  if (this.enabled !== null && this.enabled !== undefined) {
    output.writeFieldBegin('enabled', Thrift.Type.BOOL, 1);
    output.writeBool(this.enabled);
    output.writeFieldEnd();
  }
  if (this.zmq_url !== null && this.zmq_url !== undefined) {
    output.writeFieldBegin('zmq_url', Thrift.Type.STRING, 2);
    output.writeString(this.zmq_url);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

const StatsAgentParams = module.exports.StatsAgentParams = function(args) {
  this.sources = null;
  if (args) {
    if (args.sources !== undefined && args.sources !== null) {
      this.sources = Thrift.copyMap(args.sources, [ttypes.StatsAgentSource]);
    }
  }
};
StatsAgentParams.prototype = {};
StatsAgentParams.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    const ret = input.readFieldBegin();
    const fname = ret.fname;
    const ftype = ret.ftype;
    const fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.MAP) {
        let _size10 = 0;
        var _rtmp314;
        this.sources = {};
        let _ktype11 = 0;
        let _vtype12 = 0;
        _rtmp314 = input.readMapBegin();
        _ktype11 = _rtmp314.ktype;
        _vtype12 = _rtmp314.vtype;
        _size10 = _rtmp314.size;
        for (let _i15 = 0; _i15 < _size10; ++_i15) {
          let key16 = null;
          let val17 = null;
          key16 = input.readString();
          val17 = new ttypes.StatsAgentSource();
          val17.read(input);
          this.sources[key16] = val17;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatsAgentParams.prototype.write = function(output) {
  output.writeStructBegin('StatsAgentParams');
  if (this.sources !== null && this.sources !== undefined) {
    output.writeFieldBegin('sources', Thrift.Type.MAP, 1);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRUCT, Thrift.objectLength(this.sources));
    for (const kiter18 in this.sources) {
      if (this.sources.hasOwnProperty(kiter18)) {
        const viter19 = this.sources[kiter18];
        output.writeString(kiter18);
        viter19.write(output);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

const NodeConfig = module.exports.NodeConfig = function(args) {
  this.envParams = null;
  this.fwParams = null;
  this.logTailParams = null;
  this.statsAgentParams = null;
  this.sysParams = null;
  this.kvstoreParams = null;
  this.popParams = null;
  if (args) {
    if (args.envParams !== undefined && args.envParams !== null) {
      this.envParams = new ttypes.NodeEnvParams(args.envParams);
    }
    if (args.fwParams !== undefined && args.fwParams !== null) {
      this.fwParams = new FwOptParams_ttypes.NodeFwParams(args.fwParams);
    }
    if (args.logTailParams !== undefined && args.logTailParams !== null) {
      this.logTailParams = new ttypes.LogTailParams(args.logTailParams);
    }
    if (args.statsAgentParams !== undefined && args.statsAgentParams !== null) {
      this.statsAgentParams = new ttypes.StatsAgentParams(args.statsAgentParams);
    }
    if (args.sysParams !== undefined && args.sysParams !== null) {
      this.sysParams = new ttypes.SystemParams(args.sysParams);
    }
    if (args.kvstoreParams !== undefined && args.kvstoreParams !== null) {
      this.kvstoreParams = Thrift.copyMap(args.kvstoreParams, [null]);
    }
    if (args.popParams !== undefined && args.popParams !== null) {
      this.popParams = new ttypes.PopConfigParams(args.popParams);
    }
  }
};
NodeConfig.prototype = {};
NodeConfig.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    const ret = input.readFieldBegin();
    const fname = ret.fname;
    const ftype = ret.ftype;
    const fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.envParams = new ttypes.NodeEnvParams();
        this.envParams.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.fwParams = new FwOptParams_ttypes.NodeFwParams();
        this.fwParams.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.logTailParams = new ttypes.LogTailParams();
        this.logTailParams.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRUCT) {
        this.statsAgentParams = new ttypes.StatsAgentParams();
        this.statsAgentParams.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.sysParams = new ttypes.SystemParams();
        this.sysParams.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.MAP) {
        let _size20 = 0;
        var _rtmp324;
        this.kvstoreParams = {};
        let _ktype21 = 0;
        let _vtype22 = 0;
        _rtmp324 = input.readMapBegin();
        _ktype21 = _rtmp324.ktype;
        _vtype22 = _rtmp324.vtype;
        _size20 = _rtmp324.size;
        for (let _i25 = 0; _i25 < _size20; ++_i25) {
          let key26 = null;
          let val27 = null;
          key26 = input.readString();
          val27 = input.readString();
          this.kvstoreParams[key26] = val27;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRUCT) {
        this.popParams = new ttypes.PopConfigParams();
        this.popParams.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

NodeConfig.prototype.write = function(output) {
  output.writeStructBegin('NodeConfig');
  if (this.envParams !== null && this.envParams !== undefined) {
    output.writeFieldBegin('envParams', Thrift.Type.STRUCT, 1);
    this.envParams.write(output);
    output.writeFieldEnd();
  }
  if (this.fwParams !== null && this.fwParams !== undefined) {
    output.writeFieldBegin('fwParams', Thrift.Type.STRUCT, 2);
    this.fwParams.write(output);
    output.writeFieldEnd();
  }
  if (this.logTailParams !== null && this.logTailParams !== undefined) {
    output.writeFieldBegin('logTailParams', Thrift.Type.STRUCT, 3);
    this.logTailParams.write(output);
    output.writeFieldEnd();
  }
  if (this.statsAgentParams !== null && this.statsAgentParams !== undefined) {
    output.writeFieldBegin('statsAgentParams', Thrift.Type.STRUCT, 4);
    this.statsAgentParams.write(output);
    output.writeFieldEnd();
  }
  if (this.sysParams !== null && this.sysParams !== undefined) {
    output.writeFieldBegin('sysParams', Thrift.Type.STRUCT, 5);
    this.sysParams.write(output);
    output.writeFieldEnd();
  }
  if (this.kvstoreParams !== null && this.kvstoreParams !== undefined) {
    output.writeFieldBegin('kvstoreParams', Thrift.Type.MAP, 6);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.kvstoreParams));
    for (const kiter28 in this.kvstoreParams) {
      if (this.kvstoreParams.hasOwnProperty(kiter28)) {
        const viter29 = this.kvstoreParams[kiter28];
        output.writeString(kiter28);
        output.writeString(viter29);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.popParams !== null && this.popParams !== undefined) {
    output.writeFieldBegin('popParams', Thrift.Type.STRUCT, 7);
    this.popParams.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

