# Generated by Django 2.1.1 on 2018-10-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181004_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlehoptest',
            name='ping_output_blob',
            field=models.TextField(blank=True, null=True),
        ),
    ]
