# Generated by Django 2.1.1 on 2018-11-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181011_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlehoptest',
            name='iperf_pushed_throughput',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testrunexecution',
            name='topology_id',
            field=models.IntegerField(null=True),
        ),
    ]
