# Generated by Django 2.1.1 on 2018-11-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_auto_20181114_0436")]

    operations = [
        migrations.AddField(
            model_name="testrunexecution",
            name="topology_name",
            field=models.CharField(default="", max_length=256),
        )
    ]
