# Generated by Django 2.1.1 on 2019-02-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181215_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrunexecution',
            old_name='end_date',
            new_name='end_date_utc',
        ),
        migrations.RenameField(
            model_name='testrunexecution',
            old_name='start_date',
            new_name='start_date_utc',
        ),
        migrations.AlterField(
            model_name='testrunexecution',
            name='expected_end_time',
            field=models.IntegerField(default=1549051182.9337838),
        ),
    ]
