# Generated by Django 2.1.1 on 2019-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190222_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='end_time',
            new_name='end_date_utc',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='start_time',
            new_name='start_date_utc',
        ),
    ]
