# Generated by Django 2.1.1 on 2019-04-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190319_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_minute', models.CharField(default='', max_length=120)),
                ('cron_hour', models.CharField(default='', max_length=120)),
                ('cron_day_of_month', models.CharField(default='', max_length=120)),
                ('cron_month', models.CharField(default='', max_length=120)),
                ('cron_day_of_week', models.CharField(default='', max_length=120)),
                ('priority', models.IntegerField(null=True)),
                ('asap', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.IntegerField(choices=[(1, 'RUNNING'), (2, 'FINISHED'), (3, 'ABORTED'), (4, 'FAILED'), (5, 'SCHEDULED'), (6, 'QUEUED')], default=0),
        ),
        migrations.AlterField(
            model_name='testrunexecution',
            name='status',
            field=models.IntegerField(choices=[(1, 'RUNNING'), (2, 'FINISHED'), (3, 'ABORTED'), (4, 'FAILED'), (5, 'SCHEDULED'), (6, 'QUEUED')], default=0),
        ),
        migrations.AddField(
            model_name='testschedule',
            name='test_run_execution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TestRunExecution'),
        ),
    ]
