{
 "title": "Link Dashboard Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "query": "label_values(network)" },
   {
    "name": "link_name",
    "label": "select link name",
    "query": "query_result(snr{network=\"$network\"} offset ${__range_s}s)"
   },
   {
    "name": "nodeA_name",
    "label": "select nodeA",
    "query": "label_values(snr{network=\"$network\",linkName=\"$link_name\"}, nodeName)"
   },
   {
    "name": "nodeZ_name",
    "label": "nodeZ (no select)",
    "query": "label_values(snr{network=\"$network\",linkName=\"$link_name\",nodeName!=\"$nodeA_name\"}, nodeName)"
   },
   {
    "name": "nodeA",
    "label": "nodeA (no select)",
    "query": "label_values(snr{network=\"$network\",linkName=\"$link_name\",nodeName=\"$nodeA_name\"}, radioMac)"
   },
   {
    "name": "nodeZ",
    "label": "nodeZ (no select)",
    "query": "label_values(snr{network=\"$network\",linkName=\"$link_name\",nodeName=\"$nodeZ_name\"}, radioMac)"
   },
   { "name": "intervalSec", "label": "write interval (sec)", "query": "1,30" }
  ]
 },
 "panels": [
  {
   "title": "SNR A->Z",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeA]]_phystatus_ssnrest{radioMac=\"[[nodeZ]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_phystatus_ssnrest"
    },
    {
     "expr": "tgf_[[nodeA]]_phystatus_spostsnrdb{radioMac=\"[[nodeZ]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_phystatus_spostsnrdb"
    }
   ]
  },
  {
   "title": "SNR Z->A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeZ]]_phystatus_ssnrest{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_phystatus_ssnrest"
    },
    {
     "expr": "tgf_[[nodeZ]]_phystatus_spostsnrdb{radioMac=\"[[nodeA]]\" ,intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_phystatus_spostsnrdb"
    }
   ]
  },
  {
   "title": "PER A->Z",
   "type": "graph",
   "description": "based on PERE6",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeZ]]_stapkt_pere6{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}*(.000001)",
     "legendFormat": "tgf_[[nodeZ]]_stapkt_pere6"
    },
    {
     "expr": "tgf_[[nodeA]]_stapkt_rxpere6{radioMac=\"[[nodeZ]]\",intervalSec=\"[[intervalSec]]\"}*(.000001)",
     "legendFormat": "tgf_[[nodeA]]_stapkt_rxpere6"
    }
   ]
  },
  {
   "title": "PER Z->A",
   "type": "graph",
   "description": "based on PERE6",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeA]]_stapkt_pere6{radioMac=\"[[nodeZ]]\",intervalSec=\"[[intervalSec]]\"}*(.000001)",
     "legendFormat": "tgf_[[nodeA]]_stapkt_pere6"
    },
    {
     "expr": "tgf_[[nodeZ]]_stapkt_rxpere6{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}*(.000001)",
     "legendFormat": "tgf_[[nodeZ]]_stapkt_rxpere6"
    }
   ]
  },
  {
   "title": "MCS A->Z",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeZ]]_stapkt_mcs{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_stapkt_mcs"
    }
   ]
  },
  {
   "title": "MCS Z->A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeA]]_stapkt_mcs{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_stapkt_mcs"
    }
   ]
  },
  {
   "title": "mgmtlinkup/linkavailable A->Z",
   "type": "graph",
   "description": "mgmtlinkup - linkavailable --> if this changes, indicates LINK_UP_DATADOWN state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeZ]]_stapkt_mgmtlinkup{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_stapkt_mgmtlinkup"
    },
    {
     "expr": "tgf_[[nodeZ]]_stapkt_mgmtlinkup{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}-tgf_[[nodeZ]]_stapkt_linkavailable{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "delta(mgmtlinkup, linkavailable)"
    }
   ]
  },
  {
   "title": "mgmtlinkup/linkavailable Z->A",
   "type": "graph",
   "description": "mgmtlinkup - linkavailable --> if this changes, indicates LINK_UP_DATADOWN state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeZ]]_stapkt_mgmtlinkup{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_stapkt_mgmtlinkup"
    },
    {
     "expr": "tgf_[[nodeA]]_stapkt_mgmtlinkup{radioMac=\"[[nodeZ]]\",intervalSec=\"[[intervalSec]]\"}-tgf_[[nodeA]]_stapkt_linkavailable{radioMac=\"[[nodeZ]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "delta(mgmtlinkup,linkavailable)"
    }
   ]
  },
  {
   "title": "tx power index A->Z",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeZ]]_stapkt_txpowerindex{radioMac=\"[[nodeA]]\",intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_stapkt_txpowerindex"
    }
   ]
  },
  {
   "title": "tx power index Z->A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeA]]_stapkt_txpowerindex{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_stapkt_txpowerindex"
    }
   ]
  },
  {
   "title": "RSSI A->Z",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeA]]_phystatus_srssi{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_phystatus_srssi"
    },
    {
     "expr": "tgf_[[nodeA]]_phystatusdata_srssi{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_phystatusdata_srssi"
    }
   ]
  },
  {
   "title": "RSSI Z->A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeZ]]_phystatus_srssi{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_phystatus_srssi"
    },
    {
     "expr": "tgf_[[nodeZ]]_phystatusdata_srssi{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_phystatusdata_srssi"
    }
   ]
  },
  {
   "title": "PPDU A->Z",
   "type": "graph",
   "description": "if delta(txppdu) >> delta(rxppdu) indicates missing PPDUs\n\nplots tx (rx) PPDU count (i) - tx(rx) PPDU count (i-60s)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(tgf_[[nodeA]]_stapkt_rxppdu{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeA]]_stapkt_rxppdu)"
    },
    {
     "expr": "delta(tgf_[[nodeZ]]_stapkt_txppdu{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeZ]]_stapkt_txppdu)"
    }
   ]
  },
  {
   "title": "PPDU Z->A",
   "type": "graph",
   "description": "if delta(txppdu) >> delta(rxppdu) indicates missing PPDUs\n\nplots tx (rx) PPDU count (i) - tx(rx) PPDU count (i-60s)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(tgf_[[nodeZ]]_stapkt_rxppdu{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeZ]]_stapkt_rxppdu)"
    },
    {
     "expr": "delta(tgf_[[nodeA]]_stapkt_txppdu{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeA]]_stapkt_txppdu)"
    }
   ]
  },
  {
   "title": "BA A->Z",
   "type": "graph",
   "description": "if delta(txBA) >> delta(rxBA) indicates missing block acks\n\nplots tx (rx) BA count (i) - tx(rx) BA count (i-60s)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(tgf_[[nodeA]]_stapkt_rxba{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeA]]_stapkt_rxba)"
    },
    {
     "expr": "delta(tgf_[[nodeZ]]_stapkt_txba{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeZ]]_stapkt_txba)"
    }
   ]
  },
  {
   "title": "BA Z->A",
   "type": "graph",
   "description": "if delta(txBA) >> delta(rxBA) indicates missing block acks\n\nplots tx (rx) BA count (i) - tx(rx) BA count (i-60s)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(tgf_[[nodeZ]]_stapkt_rxba{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeZ]]_stapkt_rxba)"
    },
    {
     "expr": "delta(tgf_[[nodeA]]_stapkt_txba{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeA]]_stapkt_txba)"
    }
   ]
  },
  {
   "title": "MPDU count per minute A->Z",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(tgf_[[nodeZ]]_stapkt_txok{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeZ]]_stapkt_txok)"
    },
    {
     "expr": "delta(tgf_[[nodeZ]]_stapkt_txfail{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeZ]]_stapkt_txfail)"
    }
   ]
  },
  {
   "title": "MPDU count per minute Z->A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(tgf_[[nodeA]]_stapkt_txok{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeA]]_stapkt_txok)"
    },
    {
     "expr": "delta(tgf_[[nodeA]]_stapkt_txfail{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}[1m])",
     "legendFormat": "delta(tgf_[[nodeA]]_stapkt_txfail)"
    }
   ]
  },
  {
   "title": "beam indices A->Z",
   "type": "graph",
   "description": "tx beam is at nodeA and rx beam is at nodeZ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeZ]]_phyperiodic_txbeamidx{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_phyperiodic_txbeamidx"
    },
    {
     "expr": "tgf_[[nodeA]]_phyperiodic_rxbeamidx{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_phyperiodic_rxbeamidx"
    }
   ]
  },
  {
   "title": "beam indices Z->A",
   "type": "graph",
   "description": "tx beam is at nodeZ and rx beam is at nodeA",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tgf_[[nodeA]]_phyperiodic_txbeamidx{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeA]]_phyperiodic_txbeamidx"
    },
    {
     "expr": "tgf_[[nodeZ]]_phyperiodic_rxbeamidx{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "tgf_[[nodeZ]]_phyperiodic_rxbeamidx"
    }
   ]
  },
  {
   "title": "E2E Minion Uptime at Node A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_uptime{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "e2e_minion_uptime"
    },
    {
     "expr": "uptime{radioMac=\"[[nodeA]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "E2E Minion Uptime at Node Z",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "e2e_minion_uptime{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "e2e_minion_uptime"
    },
    {
     "expr": "uptime{radioMac=\"[[nodeZ]]\", intervalSec=\"[[intervalSec]]\"}",
     "legendFormat": "uptime"
    }
   ]
  }
 ]
}