{
 "title": "Network Health",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "networkName", "label": "Network Name", "query": "label_values(network)" }
  ]
 },
 "panels": [
  {
   "title": "Nodes Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "topology_online_nodes_ratio{network=\"$networkName\"} * 100"
    }
   ]
  },
  {
   "title": "Links Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "topology_online_wireless_links_ratio{network=\"$networkName\"} * 100"
    }
   ]
  },
  {
   "title": "Network RF Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "expr": "sum(tx_bytes)", "legendFormat": "bps" }
   ]
  },
  {
   "title": "Links Online",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(topology_link_is_online{network=\"$networkName\",cn=\"false\"}) * 100",
     "legendFormat": "% online"
    }
   ]
  },
  {
   "title": "Nodes Online",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(topology_node_is_online{network=\"$networkName\"}) * 100",
     "legendFormat": "% online"
    }
   ]
  },
  {
   "title": "POP VPP Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(tengigabitethernet0_if_tx_bytes{pop=\"true\",network=\"$networkName\"}) * 8",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(tengigabitethernet0_if_rx_bytes{pop=\"true\",network=\"$networkName\"}) * 8",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "POP VPP Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(tengigabitethernet0_if_tx_error_pkts{pop=\"true\",network=\"$networkName\"})",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(tengigabitethernet0_if_rx_error_pkts{pop=\"true\",network=\"$networkName\"})",
     "legendFormat": "RX"
    }
   ]
  },
  { "title": "Aggregates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "dB" }
   ],
   "targets": [
    {
     "expr": "rssi{network=\"$networkName\"}",
     "legendFormat": "{{link}} ({{linkDirection}})"
    }
   ]
  },
  {
   "title": "SnR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "snr{network=\"$networkName\"}",
     "legendFormat": "{{link}} ({{linkDirection}})"
    }
   ]
  },
  {
   "title": "PER",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "per{network=\"$networkName\"}",
     "legendFormat": "{{link}} ({{linkDirection}})"
    }
   ]
  },
  {
   "title": "MCS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mcs{network=\"$networkName\"}",
     "legendFormat": "{{link}} ({{linkDirection}})"
    }
   ]
  }
 ]
}