{
 "title": "UDP Pinger Network Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "networkName", "label": "Network Name", "query": "label_values(network)" },
   { "name": "intervalSec", "label": "Interval", "query": "label_values(intervalSec)" }
  ]
 },
 "panels": [
  { "title": "Network View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$networkName - Sample Network Availability ([[intervalSec]]s)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "1 - pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName=\"\"}"
    }
   ]
  },
  {
   "title": "$networkName - Sample Network Availability ([[intervalSec]]s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName=\"\"}"
    }
   ]
  },
  {
   "title": "$networkName - 24h Network Availability ([[intervalSec]]s)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "1 - avg_over_time(pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName=\"\"} [24h])"
    }
   ]
  },
  {
   "title": "$networkName - 24h Network Availability ([[intervalSec]]s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg_over_time(pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName=\"\"} [24h])"
    }
   ]
  },
  { "title": "Per-Node View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$networkName - Bottom 10 24h Node Availability ([[intervalSec]]s)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "bottomk(10, 1 - avg_over_time(pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName!=\"\"} [24h]))"
    }
   ]
  }
 ]
}