{
 "title": "UDP Pinger Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "networkName", "label": "Network Name", "query": "label_values(network)" },
   { "name": "intervalSec", "label": "Interval", "query": "label_values(intervalSec)" },
   {
    "name": "nodeName",
    "label": "Node Name",
    "query": "label_values(pinger_lossRatio{network=\"$networkName\"}, nodeName)"
   }
  ]
 },
 "panels": [
  { "title": "Network Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Network Availability ($networkName)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "1 - pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName=\"\"}"
    }
   ]
  },
  {
   "title": "Latest Network Availability ($networkName)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName=\"\"}"
    }
   ]
  },
  {
   "title": "24h Network Availability ($networkName)",
   "type": "gauge",
   "description": "Calculation does NOT account for missing stats.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "1 - avg_over_time(pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName=\"\"} [24h])"
    }
   ]
  },
  {
   "title": "24h Network Availability ($networkName)",
   "type": "graph",
   "description": "Calculation does NOT account for missing stats.",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg_over_time(pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName=\"\"} [24h])"
    }
   ]
  },
  {
   "title": "24h Per-Node Availability ($networkName)",
   "type": "table",
   "description": "Calculation does NOT account for missing stats.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "1 - avg_over_time(pinger_lossRatio{network=\"$networkName\", intervalSec=\"$intervalSec\", nodeName!=\"\"} [24h])"
    }
   ]
  },
  { "title": "Node Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Latest Node Availability ($networkName / $nodeName)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - pinger_lossRatio{intervalSec=\"$intervalSec\", network=\"$networkName\", nodeName=\"$nodeName\"}"
    }
   ]
  },
  {
   "title": "24h Node Availability ($networkName / $nodeName)",
   "type": "graph",
   "description": "Calculation does NOT account for missing stats.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg_over_time(pinger_lossRatio{intervalSec=\"$intervalSec\", network=\"$networkName\", nodeName=\"$nodeName\"} [24h])"
    }
   ]
  }
 ]
}