# Generated by Django 2.1.1 on 2018-12-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181116_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlehoptest',
            name='is_ecmp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlehoptest',
            name='route_changed_count',
            field=models.IntegerField(default=0),
        ),
    ]
