# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""create topology_history table

Revision ID: 0000
Revises:
Create Date: 2020-01-27 19:33:20.715224

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0000"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topology_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("network_name", sa.String(length=255), nullable=False),
        sa.Column("topology", sa.JSON(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topology_history_last_updated"),
        "topology_history",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topology_history_network_name"),
        "topology_history",
        ["network_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_topology_history_network_name"), table_name="topology_history"
    )
    op.drop_index(
        op.f("ix_topology_history_last_updated"), table_name="topology_history"
    )
    op.drop_table("topology_history")
    # ### end Alembic commands ###
