/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "BWAllocation_types.h"
#include <thrift/lib/cpp2/protocol/Protocol.h>
namespace facebook { namespace terragraph { namespace thrift {

struct BWAllocation_constants {

};

}}} // facebook::terragraph::thrift
