/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Controller_constants.h"

#include <folly/Indestructible.h>

namespace facebook { namespace terragraph { namespace thrift {

}}} // facebook::terragraph::thrift
